/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/airport": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get airport details */
    get: operations["getAirport"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Airport: {
      siteNumberCode?: string;
      icao?: string;
      iata?: string | null;
      faaCode?: string;
      city?: string;
      state?: string;
      stateCode?: string;
      country?: string;
      countryCode?: string;
      name?: string;
      keywordPrefixes?: string[];
      artccID?: string;
      artccName?: string;
      artccResponsibleID?: string;
      artccResponsibleName?: string;
      flightServiceStationID?: string;
      flightServiceStationName?: string;
      flightServiceStationPhone?: string;
      flightServiceStationAlternateID?: string | null;
      flightServiceStationAlternateName?: string | null;
      flightServiceStationAlternatePhone?: string | null;
      flightServiceStationIssuingNotamsID?: string | null;
      latitude?: number;
      longitude?: number;
      airportType?: string;
      operationalStatus?: string;
      airportAccess?: string;
      latitudeSecsNorth?: number;
      longitudeSecsEast?: number;
      elevation?: number;
      magneticVariationWest?: number;
      trafficPatternAltitudeMsl?: number | null;
      runways?: components["schemas"]["Runway"][];
      frequencies?: components["schemas"]["Frequency"][];
      remoteFrequencies?: components["schemas"]["Frequency"][];
      procedures?: components["schemas"]["Procedure"][];
      fuelTypes?: string[];
      extraServices?: string[];
      remarks?: components["schemas"]["Remark"][];
      serviceProviders?: string[];
      fbos?: string[];
      businesses?: string[];
      trafficPatternAltitudes?: string[];
      sectionalName?: string;
      managersName?: string | null;
      managersAddress?: string | null;
      managersCityStateZip?: string | null;
      managersPhoneNumber?: string | null;
      afdFilename?: string;
      diagramAvailable?: boolean;
      diagram?: string | null;
      notamDServiceAvailable?: boolean;
      towered?: boolean;
      pdc?: boolean;
      contacts?: components["schemas"]["Contact"][];
      attributes?: components["schemas"]["Attribute"][];
      schedule?: components["schemas"]["Schedule"][];
      cycle?: components["schemas"]["Cycle"];
      timezone?: components["schemas"]["Timezone"];
      source?: string;
      displayName?: string;
      latitudeInDegrees?: number;
      longitudeInDegrees?: number;
    };
    Runway: {
      ident?: string;
      length?: number;
      width?: number;
      surfaceType?: string;
      surfaceQuality?: string;
      edgeLightsIntensity?: string;
      name?: string;
      trueHeading?: number;
      magneticHeading?: number;
      latitudeBase?: number;
      longitudeBase?: number;
      approachSlopeSideBase?: string;
      approachSlopeIndicatorBase?: string;
      approachLightingSystemBase?: string;
      rightTrafficBase?: boolean;
      rightTrafficRecip?: boolean;
      recipTrueHeading?: number;
      recipMagneticHeading?: number;
      recipName?: string;
      latitudeRecip?: number;
      longitudeRecip?: number;
      approachSlopeSideRecip?: string;
      approachSlopeIndicatorRecip?: string;
      approachLightingSystemRecip?: string;
      displacedThresholdBase?: boolean;
      displacedThresholdRecip?: boolean;
      gradientBase?: number;
      gradientRecip?: number;
      displacedThresholdLengthBase?: number | null;
      displacedThresholdLengthRecip?: number | null;
      displacedThresholdLatitudeBase?: number | null;
      displacedThresholdLatitudeRecip?: number | null;
      displacedThresholdLongitudeBase?: number | null;
      displacedThresholdLongitudeRecip?: number | null;
      elevationRunwayEndBase?: number;
      elevationRunwayEndRecip?: number;
      elevationThresholdBase?: number | null;
      elevationThresholdRecip?: number | null;
      elevationTouchdownZoneBase?: number;
      elevationTouchdownZoneRecip?: number;
      glidePathAngleBase?: number | null;
      glidePathAngleRecip?: number | null;
      ldaFtDayBase?: number;
      ldaFtDayRecip?: number;
      ldaFtNightBase?: number;
      ldaFtNightRecip?: number;
      toraFtDayBase?: number;
      toraFtDayRecip?: number;
      toraFtNightBase?: number;
      toraFtNightRecip?: number;
      todaFtDayBase?: number;
      todaFtDayRecip?: number;
      todaFtNightBase?: number;
      todaFtNightRecip?: number;
      asdaFtDayBase?: number;
      asdaFtDayRecip?: number;
      asdaFtNightBase?: number;
      asdaFtNightRecip?: number;
      overrunFtBase?: number;
      overrunFtRecip?: number;
      markingsType?: string | null;
      markingsCondition?: string | null;
      attributes?: Record<string, never> | null;
      edgeLightIntensityKnown?: boolean;
      edgeLightUserPresentable?: string;
      approachSlopeIndicatorBaseAvailable?: boolean;
      approachSlopeIndicatorRecipAvailable?: boolean;
      approachLightingSystemBaseAvailable?: boolean;
      approachLightingSystemRecipAvailable?: boolean;
    };
    Frequency: {
      frequency?: number;
      name?: string;
      phone?: string | null;
      sectorDescription?: string | null;
      altitudeDescription?: string | null;
      description?: string | null;
      localFrequency?: boolean;
    };
    Procedure: {
      name?: string;
      filename?: string;
      source?: string;
      type?: string;
      airportIcao?: string;
      defaultPage?: number | null;
      associatedRunwayNames?: string[];
      georefPages?: components["schemas"]["GeorefPage"][];
      changedThisCycle?: boolean;
      fileHash?: string | null;
      pageCount?: number;
      dateLabel?: string | null;
      rotation?: number;
      lastCycleChanged?: string | null;
      georefHash?: string | null;
      procuid?: string | null;
      cycle?: components["schemas"]["Cycle"];
      procedureUrl?: string | null;
      resources?: Record<string, never>;
      pageRotations?: Record<string, never>;
      diagram?: boolean;
      icaocode?: string;
      iatacode?: string | null;
      aipcode?: string | null;
    };
    GeorefPage: {
      filename?: string;
      pageNumber?: number;
      coord1Lat?: number;
      coord1Lon?: number;
      coord2Lat?: number;
      coord2Lon?: number;
      p1PctX?: number;
      p1PctY?: number;
      p2PctX?: number;
      p2PctY?: number;
      orientation?: number;
      drawTopPct?: number;
      drawBottomPct?: number;
      drawLeftPct?: number;
      drawRightPct?: number;
      validWithinX?: number;
      validWithinY?: number;
      validWithinRadius?: number;
      excludedArea?: string | null;
      empty?: boolean;
    };
    Cycle: {
      version?: string;
      /** Format: date-time */
      dateUpdated?: string;
      /** Format: date-time */
      dateEffective?: string;
      /** Format: date-time */
      dateExpires?: string;
    };
    Timezone: {
      dstOffset?: number;
      gmtOffset?: number;
      timezoneId?: string;
    };
    Remark: {
      remarkText?: string;
    };
    Contact: {
      label?: string;
      name?: string;
      organization?: string | null;
      note?: string | null;
      addresses?: components["schemas"]["Address"][];
      phones?: components["schemas"]["Phone"][];
    };
    Address: {
      label?: string | null;
      primary?: boolean;
      rel?: string | null;
      uri?: string | null;
      physicalAddress?: string | null;
      country?: string | null;
      city?: string | null;
      state?: string | null;
      postalCode?: string | null;
      latitude?: number | null;
      longitude?: number | null;
      address?: string[];
    };
    Phone: {
      label?: string;
      phoneNumber?: string;
      primary?: boolean;
      rel?: string | null;
      uri?: string | null;
    };
    Attribute: {
      label?: string;
      value?: string;
      description?: string | null;
    };
    Schedule: {
      months?: string;
      days?: string;
      hours?: string;
      unattended?: boolean;
      irregular?: boolean;
      value?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getAirport: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response with airport details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Airport"];
        };
      };
    };
  };
}
